### ISSUE TITLE
Use servo's url crate as alternative

### ISSUE THREAD

**Issue by ivila** [bobbobbio/http_io#10]
In http_io, there is [an implementation of url](https://github.com/bobbobbio/http_io/blob/master/src/url.rs), which has some bugs(for example, it cannot handle url params).
And currently, servo has a [url crate](https://crates.io/crates/url) which support no_std, so I think we should use that as alternative.

![image](https://github.com/user-attachments/assets/bf21a3b9-426c-4914-8fdb-796e66739d46)

**Comment by ivila** [comment]
@bobbobbio Can you spend some time on this feature request? I am willing to open a PR if you permit this.

**Comment by bobbobbio** [comment]
Hey, sorry I meant to reply to your previous message.
I agree this seems like a good idea in theory. I don't have time at the moment to implement this myself anytime soon, but I would be more than happy to help someone else do it by way of reviewing a PR and providing feedback.
